apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: sharkhack
  name: sharkhack-0
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    run: sharkhack
  type: LoadBalancer
status:
  loadBalancer: {}
